# Site settings
title: AboutMe
email: wyatt.petryshen@ucalgary.ca
description: > # this means to ignore newlines until "baseurl:"
  This page provides readers an overview of my work, current interests, and future aspirations. Continue reading to learn more!
baseurl: "/AboutMePage/" # the subpath of your site, e.g. /blog/
url: "https://wyattsp.github.io" # the base hostname & protocol for your site

# User setting
owner: Wyatt Petryshen
email: wyatt.petryshen@ucalgary.ca
github_username: WyattSP
research_gate: Wyatt Petryshen
# Feel free to add more lines here

# API settings
google_api_key:

# Build settings
markdown: kramdown
