# Site settings
title: AboutMe
email: wyatt.petryshen@ucalgary.ca
description: > # this means to ignore newlines until "baseurl:"
  This page provides readers an overview of my work, current interests, and future aspirations. Continue reading to learn more!
baseurl: "/Wyatt-Petryshen" # the subpath of your site, e.g. /blog/
url: "https://wyattsp.github.io" # the base hostname & protocol for your site

# User setting
owner: Wyatt Petryshen
email: wyatt.petryshen@ucalgary.ca
github_username: WyattSP
research_gate: Wyatt Petryshen

# Build settings
markdown: kramdown

relative_links:
  enable: true
  collections: true

plugins:
  - jekyll-relative-links

include:
  - research.md
  - publications.md
  - explore.md

google_analytics: G-43370HYJ5Q
